spring:
  application:
    name: s31719-TPO04-Blog
  h2:
    console:
      path: /my-h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:blog
    username: s31719
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
#      data-locations: classpath:sql-data/users.sql,
#                      classpath:sql-data/blog.sql,
#                      classpath:sql-data/article.sql,
#                      classpath:sql-data/role.sql,
#                      classpath:sql-data/user_roles.sql