INSERT INTO users (email)
VALUES ('slava@gmail.com'),
       ('arsen@pjwstk.edu.pl'),
       ('s31719@pjwstk.edu.pl'),
       ('someUser@gmail.com'),
       ('rrrvitalrrr@gmail.com'),
       ('vitalvital1989@gmail.com'),
       ('artem.gatsuta_lopata3000@gmail.com'),
       ('whatever123@something.com'),
       ('polska@gmail.com'),
       ('german@gmail.com'),
       ('USA@gmail.com'),
       ('appleAndroid@gmail.com'),
       ('pawel_2004@gmail.com'),
       ('vitalii-2005@gmail.com'),
       ('viktoria_2001@gmail.com'),
       ('denis_1994@gmail.com'),
       ('tuxqeq@gmail.com'),
       ('ovsidee@gmail.com'),
       ('babyska90123@gmail.com'),
       ('ilyaNesma4niy@gmail.com');

INSERT INTO blog (name, manager_id)
VALUES ('PRI Blog', 1),
       ('MUL Blog', 2),
       ('PPY Blog', 3),
       ('APBD Blog', 4),
       ('NAI Blog', 5),
       ('ASD Blog', 6),
       ('ANG Blog', 7),
       ('SYC Blog', 8),
       ('TAK Blog', 9),
       ('PPJ Blog', 10),
       ('ALG Blog', 11),
       ('SBD Blog', 12),
       ('RBD Blog', 13),
       ('WSI Blog', 14),
       ('SKJ Blog', 15),
       ('WDZ Blog', 16),
       ('PJC Blog', 17),
       ('GUI Blog', 18),
       ('AM Blog', 19),
       ('MAD Blog', 20);

INSERT INTO article (title, author_id, blog_id)
VALUES ('Fight Club', 1, 1),
       ('Interstellar', 2, 2),
       ('The Prestige', 3, 3),
       ('The Dark Knight', 4, 4),
       ('The Dark Knight Rises', 5, 5),
       ('Investing Basics', 6, 6),
       ('Dune', 7, 7),
       ('Dunkirk', 8, 8),
       ('Memento', 9, 9),
       ('Oppenheimer', 10, 10),
       ('Tenet', 11, 11),
       ('Skazani na Shawshank', 12, 12),
       ('Seven', 13, 13),
       ('Nice person', 14, 14),
       ('Butterfly effect', 15, 15),
       ('Shutter Island', 16, 16),
       ('Stonehearst Asylum', 17, 17),
       ('Imitation game', 18, 18),
       ('Joker', 19, 19),
       ('Spider-man', 20, 20);

INSERT INTO role (name)
VALUES ('Admin'),
       ('Editor'),
       ('Writer'),
       ('Reader'),
       ('IT Specialist'),
       ('Java Developer'),
       ('C++ Developer'),
       ('Rust Developer'),
       ('DevOps'),
       ('CEO'),
       ('Teacher'),
       ('Manager'),
       ('Front-End developer'),
       ('Senior Developer'),
       ('Intern'),
       ('Middle Java Developer'),
       ('Junior Java Developer'),
       ('SEO Specialist'),
       ('SEO Specialist'),
       ('Interpreter'),
       ('Psychologist'),
       ('Lawyer');


INSERT INTO user_roles (user_id, role_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 1),
       (6, 2),
       (7, 3),
       (8, 4),
       (9, 1),
       (10, 2),
       (11, 3),
       (12, 4),
       (13, 1),
       (14, 2),
       (15, 3),
       (16, 4),
       (17, 1),
       (18, 2),
       (19, 3),
       (20, 4);
