INSERT INTO users (email)
VALUES ('user1@example.com'),
       ('user2@example.com'),
       ('user3@example.com'),
       ('user4@example.com'),
       ('user5@example.com'),
       ('user6@example.com'),
       ('user7@example.com'),
       ('user8@example.com'),
       ('user9@example.com'),
       ('user10@example.com'),
       ('user11@example.com'),
       ('user12@example.com'),
       ('user13@example.com'),
       ('user14@example.com'),
       ('user15@example.com'),
       ('user16@example.com'),
       ('user17@example.com'),
       ('user18@example.com'),
       ('user19@example.com'),
       ('user20@example.com');

INSERT INTO blog (name, manager_id)
VALUES ('Tech Blog', 1),
       ('Travel Blog', 2),
       ('Food Blog', 3),
       ('Fitness Blog', 4),
       ('Fashion Blog', 5),
       ('Finance Blog', 6),
       ('Gaming Blog', 7),
       ('Science Blog', 8),
       ('Music Blog', 9),
       ('Art Blog', 10),
       ('Books Blog', 11),
       ('History Blog', 12),
       ('Photography Blog', 13),
       ('DIY Blog', 14),
       ('Movie Blog', 15),
       ('Sports Blog', 16),
       ('Health Blog', 17),
       ('News Blog', 18),
       ('Nature Blog', 19),
       ('Education Blog', 20);

INSERT INTO article (title, author_id, blog_id)
VALUES ('Spring Boot Guide', 1, 1),
       ('JPA Deep Dive', 2, 2),
       ('Traveling to Japan', 3, 3),
       ('Best Workout Routines', 4, 4),
       ('Latest Fashion Trends', 5, 5),
       ('Investing Basics', 6, 6),
       ('Top 10 Games of 2024', 7, 7),
       ('Quantum Physics Explained', 8, 8),
       ('Music Theory 101', 9, 9),
       ('Modern Art Movements', 10, 10),
       ('Must-Read Books', 11, 11),
       ('Ancient Civilizations', 12, 12),
       ('Photography Techniques', 13, 13),
       ('DIY Home Decor', 14, 14),
       ('Oscar-Winning Movies', 15, 15),
       ('Football Strategies', 16, 16),
       ('Mental Health Tips', 17, 17),
       ('Breaking News', 18, 18),
       ('Wildlife Conservation', 19, 19),
       ('Effective Learning Strategies', 20, 20);

INSERT INTO role (name)
VALUES ('Admin'),
       ('Editor'),
       ('Writer'),
       ('Reader');

INSERT INTO user_roles (user_id, role_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 1),
       (6, 2),
       (7, 3),
       (8, 4),
       (9, 1),
       (10, 2),
       (11, 3),
       (12, 4),
       (13, 1),
       (14, 2),
       (15, 3),
       (16, 4),
       (17, 1),
       (18, 2),
       (19, 3),
       (20, 4);
