INSERT INTO article (title, author_id, blog_id)
VALUES ('Spring Boot Guide', 1, 1),
       ('JPA Deep Dive', 2, 2),
       ('Traveling to Japan', 3, 3),
       ('Best Workout Routines', 4, 4),
       ('Latest Fashion Trends', 5, 5),
       ('Investing Basics', 6, 6),
       ('Top 10 Games of 2024', 7, 7),
       ('Quantum Physics Explained', 8, 8),
       ('Music Theory 101', 9, 9),
       ('Modern Art Movements', 10, 10),
       ('Must-Read Books', 11, 11),
       ('Ancient Civilizations', 12, 12),
       ('Photography Techniques', 13, 13),
       ('DIY Home Decor', 14, 14),
       ('Oscar-Winning Movies', 15, 15),
       ('Football Strategies', 16, 16),
       ('Mental Health Tips', 17, 17),
       ('Breaking News', 18, 18),
       ('Wildlife Conservation', 19, 19),
       ('Effective Learning Strategies', 20, 20);