INSERT INTO blog (name, manager_id)
VALUES ('Tech Blog', 1),
       ('Travel Blog', 2),
       ('Food Blog', 3),
       ('Fitness Blog', 4),
       ('Fashion Blog', 5),
       ('Finance Blog', 6),
       ('Gaming Blog', 7),
       ('Science Blog', 8),
       ('Music Blog', 9),
       ('Art Blog', 10),
       ('Books Blog', 11),
       ('History Blog', 12),
       ('Photography Blog', 13),
       ('DIY Blog', 14),
       ('Movie Blog', 15),
       ('Sports Blog', 16),
       ('Health Blog', 17),
       ('News Blog', 18),
       ('Nature Blog', 19),
       ('Education Blog', 20);