spring:
  application:
    name: s31719-TPO04-Books
  h2:
    console:
      path: /my-h2-console
  datasource:
    url: jdbc:h2:mem:books
    username: s31719
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always