--publisher:
INSERT INTO Publisher (Name, Surname)
VALUES ('Arsen', 'Kolopav'),
       ('Artem', 'Gatusta'),
       ('Illya', 'Nesmachniy'),
       ('Vitalii', 'Korytnyi'),
       ('Maksym', 'Lototskyi'),
       ('Viktoria', 'Kharchenko'),
       ('Diana', 'Targoni'),
       ('Djiana', 'Korichnevaya'),
       ('Ivan', 'Svin'),
       ('Slava', 'Larin'),
       ('Katya', 'Vinokurova'),
       ('Marina', 'Korytna'),
       ('Kevin', 'Kolopav'),
       ('Sofia', 'Gillmavnt'),
       ('Kira', 'Martynenko'),
       ('Ihor', 'Bykova'),
       ('Nasar', 'Chaika'),
       ('Kamil', 'Mamedov'),
       ('Egor', 'Misin'),
       ('Danya', 'Kiktenko');

-- book
INSERT INTO Book (Title, Publisher_id)
VALUES ('Spring Boot In Action 5', 1),
       ('Spring Boot In Action 3', 2),
       ('C++ For Kids', 3),
       ('Fight Club', 4),
       ('Interstellar. Science behind.', 5),
       ('Shuttered Island', 6),
       ('Looking for Alaska', 7),
       ('The Bluest Eye', 8),
       ('Mathematical Analysis', 9),
       ('Linear Algebra', 10),
       ('Linear Geometry', 11),
       ('Animal Farm', 12),
       ('Lord of the Flies', 13),
       ('To Kill a Mockingbird', 14),
       ('The Catcher in the Rye', 15),
       ('Artificial Intelligence In Action', 16),
       ('PPJ Lecture', 17),
       ('Business Partner English C1', 18),
       ('The Handmaid', 19),
       ('Beloved', 20);

-- author
INSERT INTO Author (Name)
VALUES ('Hanna Bitsayeva'),
       ('Sviatoslav Vasylenko'),
       ('Kateryna Vynokurova'),
       ('Oleksandr Voroshylo'),
       ('Marianna Herlanets'),
       ('Rostyslav Horiukhin'),
       ('Danii Drobnyi'),
       ('Mariia Katolyk'),
       ('Maksym Kirpikin'),
       ('Natalia Kitaieva'),
       ('Yuliia Klymenko'),
       ('Vitalii Korytnyi'),
       ('Oleksandr Kulish'),
       ('Anastasiia Lohinova'),
       ('Daryna Lutsenko'),
       ('Vasylina Mykhneva'),
       ('Yehor Mashkovskyi'),
       ('Ihor Panchenko'),
       ('Denys Perepechai'),
       ('Artem Ponomarenko'),
       ('Maksym Popov'),
       ('Dmytro Prudko'),
       ('Diana Rychko'),
       ('Yevdokiia Rozdobudko');

-- Book_Author
INSERT INTO Book_Author (Book_id, Author_id)
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (5, 9),
       (5, 10),
       (6, 11),
       (6, 12),
       (7, 13),
       (7, 14),
       (8, 15),
       (8, 16),
       (9, 17),
       (9, 18),
       (10, 19),
       (10, 20),
       (11, 1),
       (11, 3),
       (12, 5),
       (12, 7),
       (13, 9),
       (13, 11),
       (14, 13),
       (14, 15),
       (15, 17),
       (15, 19),
       (16, 2),
       (16, 4),
       (17, 6),
       (17, 8),
       (18, 10),
       (18, 12),
       (19, 14),
       (19, 16),
       (20, 18),
       (20, 20);