--publisher:
INSERT INTO Publisher (Name, Surname)
VALUES ('John', 'Doe'),
       ('Jane', 'Smith'),
       ('Emily', 'Johnson'),
       ('Michael', 'Brown'),
       ('Chris', 'White'),
       ('Sarah', 'Davis'),
       ('Robert', 'Miller'),
       ('Laura', 'Wilson'),
       ('James', 'Moore'),
       ('Lisa', 'Taylor'),
       ('David', 'Anderson'),
       ('Susan', 'Thomas'),
       ('Kevin', 'Harris'),
       ('Amy', 'Clark'),
       ('Daniel', 'Lewis'),
       ('Nancy', 'Robinson'),
       ('Paul', 'Walker'),
       ('Emma', 'Hall'),
       ('Ryan', 'Young'),
       ('Sophia', 'Allen');

-- book
INSERT INTO Book (Title, Publisher_id)
VALUES ('The Great Adventure', 1),
       ('Mystery of the Lost City', 2),
       ('Science Wonders', 3),
       ('History Unveiled', 4),
       ('The Art of War', 5),
       ('Cooking 101', 6),
       ('Romance in Paris', 7),
       ('Deep Space', 8),
       ('Programming in Java', 9),
       ('Database Essentials', 10),
       ('Travel the World', 11),
       ('Gardening for Beginners', 12),
       ('The Secret Garden', 13),
       ('Fictional Tales', 14),
       ('Cybersecurity Basics', 15),
       ('Artificial Intelligence', 16),
       ('Business Strategies', 17),
       ('Marketing in Digital Age', 18),
       ('Financial Planning', 19),
       ('Healthy Living', 20);

-- author
INSERT INTO Author (Name)
VALUES ('William Shakespeare'),
       ('Mark Twain'),
       ('Jane Austen'),
       ('Ernest Hemingway'),
       ('J.K. Rowling'),
       ('George Orwell'),
       ('F. Scott Fitzgerald'),
       ('Charles Dickens'),
       ('Leo Tolstoy'),
       ('Agatha Christie'),
       ('Stephen King'),
       ('J.R.R. Tolkien'),
       ('Harper Lee'),
       ('Isaac Asimov'),
       ('H.G. Wells'),
       ('Virginia Woolf'),
       ('Arthur Conan Doyle'),
       ('Edgar Allan Poe'),
       ('Emily Brontë'),
       ('Oscar Wilde');

-- Book_Author
INSERT INTO Book_Author (Book_id, Author_id)
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (5, 9),
       (5, 10),
       (6, 11),
       (6, 12),
       (7, 13),
       (7, 14),
       (8, 15),
       (8, 16),
       (9, 17),
       (9, 18),
       (10, 19),
       (10, 20),
       (11, 1),
       (11, 3),
       (12, 5),
       (12, 7),
       (13, 9),
       (13, 11),
       (14, 13),
       (14, 15),
       (15, 17),
       (15, 19),
       (16, 2),
       (16, 4),
       (17, 6),
       (17, 8),
       (18, 10),
       (18, 12),
       (19, 14),
       (19, 16),
       (20, 18),
       (20, 20);