CREATE TABLE IF NOT EXISTS Publisher (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Surname VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Price INT NOT NULL,
    Publisher_id BIGINT NOT NULL,
    CONSTRAINT fk_book_publisher FOREIGN KEY (Publisher_id) REFERENCES Publisher (ID)
);

CREATE TABLE IF NOT EXISTS Author (
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book_Author (
    Book_id   BIGINT NOT NULL,
    Author_id BIGINT NOT NULL,
    PRIMARY KEY (Book_id, Author_id),
    CONSTRAINT fk_book_author_book FOREIGN KEY (Book_id) REFERENCES Book (ID) ON DELETE CASCADE,
    CONSTRAINT fk_book_author_author FOREIGN KEY (Author_id) REFERENCES Author (ID) ON DELETE CASCADE
);