CREATE TABLE IF NOT EXISTS AUTHOR (
    AUTHOR_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME     VARCHAR(50)  NOT NULL,
    LAST_NAME      VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLISHER (
    PUBLISHER_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    PUBLISHER_NAME VARCHAR(100) NOT NULL,
    ADDRESS        VARCHAR(255),
    COUNTRY        VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS GENRE (
    GENRE_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    GENRE_NAME     VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS BOOK (
    BOOK_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE            VARCHAR(150) NOT NULL,
    ISBN             VARCHAR(20)  UNIQUE,
    PUBLICATION_YEAR INT,
    PUBLISHER_ID     BIGINT,
    CONSTRAINT FK_BOOK_PUBLISHER
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (PUBLISHER_ID)
);

CREATE TABLE IF NOT EXISTS BOOK_AUTHOR (
    BOOK_ID   BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    CONSTRAINT FK_BA_BOOK   FOREIGN KEY (BOOK_ID)   REFERENCES BOOK   (BOOK_ID),
    CONSTRAINT FK_BA_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS BOOK_GENRE (
    BOOK_ID  BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BG_BOOK  FOREIGN KEY (BOOK_ID)  REFERENCES BOOK  (BOOK_ID),
    CONSTRAINT FK_BG_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRE (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLE(
    USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS APP_USER (
    APP_USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME   VARCHAR(40)  NOT NULL,
    LAST_NAME    VARCHAR(40)  NOT NULL,
    EMAIL        VARCHAR(120) NOT NULL UNIQUE,
    PASSWORD     VARCHAR(10000) NOT NULL
);

CREATE TABLE IF NOT EXISTS APP_USER_ROLES (
    APP_USER_ID   BIGINT NOT NULL,
    USER_ROLE_ID  BIGINT NOT NULL,
    PRIMARY KEY (APP_USER_ID, USER_ROLE_ID),
    CONSTRAINT FK_AUR_USER FOREIGN KEY (APP_USER_ID)  REFERENCES APP_USER (APP_USER_ID),
    CONSTRAINT FK_AUR_ROLE FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLE (USER_ROLE_ID)
);
