spring:
  application:
    name: TPO03
  banner:
    location: logo-app
    charset: UTF-8
  profiles:
    active: upperCase
  h2:
    console:
      path: /my-h2-console
  datasource:
    url: jdbc:h2:file:./db/entries;
    username: s31719
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl